name: coalition_website
description: The Coalition Website

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flex_color_scheme: ^7.2.0
  carousel_slider: ^4.2.1
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter


flutter:
  assets:
    - assets/cropped-site_logo-3.png
    - assets/cropped-coalitionsmall-1.png
    - assets/cropped-beav-2.jpg

  uses-material-design: true


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets\\cropped-coalitionsmall-1.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets\\cropped-coalitionsmall-1.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets\\cropped-coalitionsmall-1.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets\\cropped-coalitionsmall-1.png"
