on:
  push:
    branches:
    - master
jobs:
   Build-Flutter-Web:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.0'
        channel: 'stable'
    - run: flutter pub get
    - run: flutter build web
    - uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_TARGET }}
        port: ${{secrets.FTP_PORT}}
        username: ${{secrets.FTP_USER}}
        password: ${{ secrets.FTP_PASS }}
        local-dir: build/web/
